- hosts: webservers
  vars_files:
    - ../vars.yaml
  remote_user: "{{ssh_user}}"
  tasks:
  - name: install base dependencies
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    loop:
      - python3
      - python3-pip
    become: true
    become_user: root
    become_method: sudo

  - name: install dependencies
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    become: true
    become_user: root
    become_method: sudo
  - name: add GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    become: true
    become_user: root
    become_method: sudo
  - name: add docker repository to apt
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present
    become: true
    become_user: root
    become_method: sudo

  - name: install docker
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    become: true
    become_user: root
    become_method: sudo

  - name: assicurati che docker sia attivo
    service:
      name: docker
      state: started
      enabled: yes
    become: true
    become_user: root
    become_method: sudo

  - name: create docker group
    become: true
    group:
      name: docker
      state: present

  - name: add user to group 
    become: true
    user:
      name: "{{ansible_user}}"
      groups: docker
      append: true

  - meta: reset_connection                # <--- must do this if using pipelining
  
  - name: install 'Docker SDK for Python'
    #become: true               <--- DO NOT DO THIS!!!
    pip:
      name: docker
  - name: install 'Docker SDK for Python'
    #become: true               <--- DO NOT DO THIS!!!
    pip:
      name: docker-compose

  - name: Download DockerCompose
    get_url:
      url: "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-Linux-x86_64"
      dest: "/usr/bin/docker-compose"
      mode: a+x
    become: true
    become_user: root
    become_method: sudo

  handlers:
    - name: restart docker
      service: 
        name: docker 
        state: restarted