- hosts: all
  vars_files:
    - vars.yaml
  remote_user: "{{ssh_user}}"
  tasks:
  - name: copy Docker Compose files
    copy:
      src: docker-compose-files/{{ item }}
      dest: "/home/{{ssh_user}}/docker-compose/{{ item }}"
    loop:
    - docker-compose.yml
    - docker-compose.prod.yml
  # use files parameter to use multiple docker-compose.yml files
  - name: deploy Docker Compose stack
    become: true
    become_user: root
    become_method: sudo
    docker_compose:
      project_src: "/home/{{ssh_user}}/docker-compose/"
      files:
      - "{{docker-compose-filename}}"

