- hosts: all
  vars_files:
    - vars.yaml
  remote_user: "{{ssh_user}}"
  tasks:
  - name: Check if Telegraf is installed
    command: dpkg-query -W telegraf
    register: my_package_check_deb
    failed_when: my_package_check_deb.rc > 1
    changed_when: my_package_check_deb.rc == 1

  - name: Download Telegraf
    get_url:
      url: "{{package_url}}"
      dest: "/home/{{ssh_user}}/telegraf_1.18.1-1_amd64.deb"
    when: my_package_check_deb.rc == 1

  - name: Install Telegraf
    apt:
      deb: "/home/{{ssh_user}}/telegraf_1.18.1-1_amd64.deb"
    become: true
    become_user: root
    become_method: sudo
    when: my_package_check_deb.rc == 1

  - name: Setup Telegraf main file
    template:
      src: "{{playbook_dir}}/configuration-files/{{config_dir}}/telegraf.conf"
      dest: "/etc/telegraf/telegraf.conf"
    become: true
    become_user: root
    become_method: sudo

  - name: Setup Telegraf configuration files
    template:
      src: "{{ item }}"
      dest: "/etc/telegraf/telegraf.d"
    become: true
    become_user: root
    become_method: sudo
    with_fileglob:
    - "{{playbook_dir}}/configuration-files//{{config_dir}}/telegraf.d/*"
  
  - name: restart Telegraf service to load configurations
    become: true
    become_user: root
    become_method: sudo
    service:
      name: telegraf
      state: restarted

